export const trendingSearches = [
  "Writing Guides",
  "Ebook Templates",
  "Content Planners",
  "Book Marketing",
  "Writing Prompts",
  "Author Tools",
  "Publishing Guides",
  "Reader Resources",
]

export const searchOperators = [
  {
    operator: "type:",
    example: "type:ebook",
    description: "Filter by resource type (ebook, guide, template, etc.)",
  },
  {
    operator: "author:",
    example: "author:writingpro",
    description: "Filter by merchant",
  },
  {
    operator: "price:",
    example: "price:<25",
    description: "Filter by price (>, <, =)",
  },
  {
    operator: "rating:",
    example: "rating:4.5",
    description: "Filter by customer rating",
  },
]

export const categories = [
  {
    name: "Writing Resources",
    subcategories: ["Writing Guides", "Grammar Tools", "Style Guides", "Writing Prompts", "Character Development"],
  },
  {
    name: "Ebooks & Guides",
    subcategories: ["How-to Guides", "Industry Reports", "Educational Content", "Self-Help", "Business Guides"],
  },
  {
    name: "Templates & Tools",
    subcategories: ["Book Templates", "Content Planners", "Editorial Calendars", "Worksheets", "Checklists"],
  },
  {
    name: "Publishing & Marketing",
    subcategories: ["Book Marketing", "Social Media Templates", "Email Templates", "Launch Strategies", "Cover Design"],
  },
  {
    name: "Reader Resources",
    subcategories: ["Book Lists", "Reading Guides", "Book Club Materials", "Discussion Questions", "Reading Trackers"],
  },
]

export const mockResources = [
  {
    id: "1",
    title: "The Complete Guide to Self-Publishing Success",
    description:
      "Comprehensive 200-page guide covering everything from writing to marketing your book. Includes templates, checklists, and step-by-step strategies used by bestselling authors. Perfect for first-time and experienced authors.",
    price: 39.99,
    originalPrice: 59.99,
    category: "Publishing & Marketing",
    subcategory: "Launch Strategies",
    tags: ["self-publishing", "book marketing", "author guide", "publishing", "bestseller"],
    images: [
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
      "/placeholder.svg?height=400&width=300",
    ],
    author: "Publishing Pro",
    authorRating: 4.9,
    authorSales: 8420,
    rating: 4.8,
    reviewCount: 342,
    downloads: 1250,
    featured: true,
    fileType: "PDF + Bonus Materials",
    fileSize: "15 MB",
    license: "Personal Use",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-15",
    inStock: true,
    variations: [
      { id: "1a", name: "Standard Edition", price: 39.99, description: "PDF guide only" },
      { id: "1b", name: "Premium Bundle", price: 79.99, description: "Guide + Templates + Video Course" },
    ],
  },
  {
    id: "2",
    title: "30-Day Content Creation Planner",
    description:
      "Never run out of content ideas again! This comprehensive planner includes 30 days of prompts, templates for social media, blog posts, and newsletters. Includes both digital and printable versions.",
    price: 19.99,
    category: "Templates & Tools",
    subcategory: "Content Planners",
    tags: ["content planning", "social media", "blog writing", "content calendar", "productivity"],
    images: ["/placeholder.svg?height=400&width=300", "/placeholder.svg?height=400&width=300"],
    author: "Content Creator Hub",
    authorRating: 4.7,
    authorSales: 12930,
    rating: 4.6,
    reviewCount: 156,
    downloads: 2890,
    featured: true,
    fileType: "PDF + Notion Template",
    fileSize: "8 MB",
    license: "Personal & Commercial",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-10",
    inStock: true,
  },
  {
    id: "3",
    title: "1000 Creative Writing Prompts Collection",
    description:
      "Overcome writer's block with this massive collection of writing prompts. Organized by genre, mood, and difficulty level. Perfect for daily writing practice, creative exercises, and story inspiration.",
    price: 14.99,
    originalPrice: 24.99,
    category: "Writing Resources",
    subcategory: "Writing Prompts",
    tags: ["writing prompts", "creative writing", "story ideas", "writer's block", "inspiration"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Creative Writer's Guild",
    authorRating: 4.8,
    authorSales: 15100,
    rating: 4.7,
    reviewCount: 289,
    downloads: 4100,
    featured: false,
    fileType: "PDF + DOCX",
    fileSize: "5 MB",
    license: "Personal Use",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-08",
    inStock: true,
  },
  {
    id: "4",
    title: "Book Marketing Toolkit - Launch Your Bestseller",
    description:
      "Complete marketing toolkit with email templates, social media graphics, press release templates, and launch timeline. Used by authors who've hit Amazon bestseller lists. Includes Canva templates.",
    price: 49.99,
    category: "Publishing & Marketing",
    subcategory: "Book Marketing",
    tags: ["book marketing", "book launch", "social media", "email marketing", "bestseller"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Bestseller Academy",
    authorRating: 4.9,
    authorSales: 6750,
    rating: 4.8,
    reviewCount: 198,
    downloads: 1680,
    featured: false,
    fileType: "PDF + Canva Templates",
    fileSize: "25 MB",
    license: "Commercial License",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-12",
    inStock: true,
  },
  {
    id: "5",
    title: "Ultimate Reading Tracker & Book Journal",
    description:
      "Beautiful, comprehensive reading tracker with space for 100 books. Includes reading goals, book ratings, favorite quotes, and reflection pages. Available in multiple colors and formats.",
    price: 12.99,
    category: "Reader Resources",
    subcategory: "Reading Trackers",
    tags: ["reading tracker", "book journal", "reading goals", "book lover", "printable"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Book Lover's Paradise",
    authorRating: 4.6,
    authorSales: 9840,
    rating: 4.5,
    reviewCount: 167,
    downloads: 3420,
    featured: false,
    fileType: "PDF (Printable)",
    fileSize: "12 MB",
    license: "Personal Use",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-14",
    inStock: true,
  },
  {
    id: "6",
    title: "Character Development Masterclass Workbook",
    description:
      "In-depth workbook for creating compelling, three-dimensional characters. Includes character sheets, development exercises, and psychological profiling templates. Used by published novelists.",
    price: 29.99,
    category: "Writing Resources",
    subcategory: "Character Development",
    tags: ["character development", "novel writing", "fiction writing", "storytelling", "creative writing"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Fiction Master Class",
    authorRating: 4.8,
    authorSales: 5200,
    rating: 4.9,
    reviewCount: 134,
    downloads: 890,
    featured: true,
    fileType: "PDF + DOCX Templates",
    fileSize: "18 MB",
    license: "Personal Use",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-16",
    inStock: true,
  },
  {
    id: "7",
    title: "Email Newsletter Templates for Authors",
    description:
      "Professional email templates designed specifically for authors. Includes welcome sequences, book launch announcements, and reader engagement templates. Compatible with all major email platforms.",
    price: 24.99,
    category: "Publishing & Marketing",
    subcategory: "Email Templates",
    tags: ["email marketing", "newsletter", "author marketing", "email templates", "reader engagement"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Author Marketing Pro",
    authorRating: 4.7,
    authorSales: 7300,
    rating: 4.6,
    reviewCount: 89,
    downloads: 1200,
    featured: false,
    fileType: "HTML + PDF Guide",
    fileSize: "6 MB",
    license: "Commercial License",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-11",
    inStock: true,
  },
  {
    id: "8",
    title: "Book Club Discussion Guide Template Pack",
    description:
      "Ready-to-use discussion guides for book clubs. Includes question templates, activity ideas, and meeting planners. Perfect for librarians, book club leaders, and reading groups.",
    price: 16.99,
    category: "Reader Resources",
    subcategory: "Book Club Materials",
    tags: ["book club", "discussion questions", "reading group", "book discussion", "literature"],
    images: ["/placeholder.svg?height=400&width=300"],
    author: "Reading Community Hub",
    authorRating: 4.5,
    authorSales: 3400,
    rating: 4.4,
    reviewCount: 67,
    downloads: 780,
    featured: false,
    fileType: "PDF + DOCX",
    fileSize: "4 MB",
    license: "Personal & Educational",
    deliveryTime: "Instant Download",
    lastUpdated: "2024-01-09",
    inStock: true,
  },
]
